[package]
name = "swc-plugin-reanimated"
version = "0.0.1"
edition = "2021"
authors = ["OJ Kwon <kwon.ohjoong@gmail.com>"]
description = ""
license = "MIT"
repository = "https://github.com/kwonoj/swc-plugin-react-native-reanimated"

[lib]
crate-type = ["cdylib"]

[dependencies]
swc_plugin = { git = "https://github.com/kwonoj/swc", rev = "a7381651eaec89c44b63575b16d5a42d83e02e96", features = ["quote"] }
swc-reanimated-worklets-visitor = { version = "0.0.1", path = "../swc-reanimated-worklets-visitor" }
serde = "1"
serde_json = "1"
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
