pub static OBJECT_HOOKS: [&str; 2] = ["useAnimatedGestureHandler", "useAnimatedScrollHandler"];

pub static POSSIBLE_OPT_FUNCTION: [&str; 1] = ["interpolate"];

pub static GLOBALS: [&str; 54] = [
    "this",
    "console",
    "performance",
    "_setGlobalConsole",
    "_chronoNow",
    "Date",
    "Array",
    "ArrayBuffer",
    "Int8Array",
    "Int16Array",
    "Int32Array",
    "Uint8Array",
    "Uint8ClampedArray",
    "Uint16Array",
    "Uint32Array",
    "Float32Array",
    "Float64Array",
    "Date",
    "HermesInternal",
    "JSON",
    "Math",
    "Number",
    "Object",
    "String",
    "Symbol",
    "undefined",
    "null",
    "UIManager",
    "requestAnimationFrame",
    "_WORKLET",
    "arguments",
    "Boolean",
    "parseInt",
    "parseFloat",
    "Map",
    "Set",
    "_log",
    "_updatePropsPaper",
    "_updatePropsFabric",
    "_removeShadowNodeFromRegistry",
    "RegExp",
    "Error",
    "global",
    "_measure",
    "_scrollTo",
    "_dispatchCommand",
    "_setGestureState",
    "_getCurrentTime",
    "_eventTimestamp",
    "_frameTimestamp",
    "isNaN",
    "LayoutAnimationRepository",
    "_stopObservingProgress",
    "_startObservingProgress",
];

pub static FUNCTIONLESS_FLAG: i32 = 0b00000001;
pub static STATEMENTLESS_FLAG: i32 = 0b00000010;
